version: '3'
services:
  client:
    image: "dck2020/multi-client-9-18"
    mem_limit: 128m
    hostname: client
  server:
    image: "dck2020/multi-server-9-18"
    mem_limit: 128m
    hostname: api
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
      - PGHOST=$PGHOST
      - PGUSER=$PGUSER
      - PGPASSWORD=$PGPASSWORD
      - PGDATABASE=$PGDATABASE
      - PGPORT=$PGPORT
  worker:
    image: "dck2020/multi-worker-9-18"
    mem_limit: 128m
    hostname: worker
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
  nginx:
    image: "dck2020/multi-nginx-9-18"
    mem_limit: 128m
    hostname: nginx
    ports:
      - "80:80"