name: Deply MultiDocker
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker login -u $ {{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t dck2020/react-test -f ./client/Dockerfile ./client
      - run: docker run -e CI=true dck2020/react-test npm test

      - run: docker build -t dck2020/multi-client-9-18 ./client
      - run: docker build -t dck2020/multi-nginx-9-18 ./nginx
      - run: docker build -t dck2020/multi-server-9-18 ./server
      - run: docker build -t dck2020/multi-worker-9-18 ./worker
      - run: docker push dck2020/multi-client-9-18
      - run: docker push dck2020/multi-nginx-9-18
      - run: docker push dck2020/multi-server-9-18
      - run: docker push dck2020/multi-worker-9-18

      - name: Generate deployment package
        run: zip -r deploy.zip . -x "*.git*" 

      - name: Deploy to AWS Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v22
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application-name: multi-docker
          environment-name: Multi-docker-env
          existing_bucker_name: elasticbeanstalk-us-west-2-590183879096
          region: us-west-2
          version-label: ${{ github.sha }}
          deployment_package: deploy.zip